### PR TITLE
Show partition name in dis/arming topic

### PR DESCRIPTION
**Pull request by kovacsbalu**
for issue #8

### CODE REVIEW

**Comment by psyciknz** [comment]
Hi

Thanks for undertaking to do this, I was going to look at it today.

1.

So the code looks ok, but if I'm correct (I've not figure out how to pull your code and run it locally here), but you will publish (with defaults in the config.ini for topics)
```
Paradox/Partition/<partitionname> <status type>
```
Where the original topic was:
```
Paradox/Partition/Status <status type>
```
Can we change your output to:
```
Paradox/Partition/<partitionname>/Status <status type>
```

So just add the "Status" part of the topic back.

2.  When connected, the system cycles through some keep alive methods.  KeepAliveStatus1 contains the partition status.
So this will need to be updated so that the Status topic is consistent with yours 
eg at the momnent you will get a live event on 
`Paradox/Partition/<partitionname>`
and then a keepalive event on 
`Paradox/Partition/Status`
With the added complication that I'm not sure at the keep alive event if you know the names of the partitions.

**Comment by psyciknz** [comment]
Hi  - do you have that maintainers can update this?  I have changes to the test_sp and IP150 files to make with some of the points I noted above.

**Comment by kovacsbalu** [comment]
Hi @psyciknz, I fixed arm state topic and logging.
For the 2nd: I think the keepalive is connected to whole system so not related to location (partition)

**Comment by psyciknz** [comment]
Keep alive 0 posts the battery status.
Keep alive 1 lists all the partition states.   I’ve got code that fixes
this.   Based on reading the partion labels at the start.

If you allow me up update your branch, and I can post it.

**Comment by kovacsbalu** [comment]
Let see, put this change to a different branch and merge if it works.

**Comment by psyciknz** [comment]
Hi.  So I've added my changes to a branch of the same name:
https://github.com/psyciknz/ParadoxIP150v2/tree/partition-names

Have a look at those.  In duplicates your changes with the events, and does
the partion names on keep alive events....but at this stage only partition
1.

**Comment by kovacsbalu** [comment]
I will test it. Can we read partition 2 also?

**Comment by kovacsbalu** [comment]
I run into an exception and maybe fixed (see below):
```
INFO:root:State03:Updating zone and alarm status
DEBUG:root:updateZoneAndAlarmStatus: Publishing initial alarm state (state:CLOSED)
ERROR:root:State03:Error reading labels: KeyError('CLOSED',) 
```
```
@@ -565,7 +565,7 @@ class paradox:
         # Skip to alarm status
         reply = reply[33:]
         alarmState = ord(reply[0])
-        alarmState = ZonesOn if (alarmState & 1) else ZonesOff
+        alarmState = self.Alarm_Partition_States['ARMED'] if (alarmState & 1) else self.Alarm_Partition_States['DISARMED']
```

**Comment by psyciknz** [comment]
> I will test it. Can we read partition 2 also?

Yeah, I just need to add the code to read all the partition bits

**Comment by psyciknz** [comment]
This will fix it.....but I think will only do partition 1...and'm not sure
at this point if we can figure out if it's partition 1 or 2....and it
proper name.

If the keepalive is doing it's job then this shouldn't be needed.

**Comment by psyciknz** [comment]
I've done a few updates in my branch.  Have a look at that.  

Tonight if I get a chance I'll restructure that keepalivestatus1 method so that it processes both partitions for you.

**Pull request merged**
